### PR TITLE
Image-Stitching

### LINKED ISSUE #338: Image Stitching
Hello @geekquad , I want to work on this issue Image Stitching . 
Could you please kindly assign me the same.

### PR DESCRIPTION
**Pull request by Saptar001**
Hello @geekquad , I made a PR on "Image Stitching of Two Images" referring to the Issue #338 .

Fixes #338 

Do go through my work and give your reviews on it. 

Thank You :)

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @Saptar001, please display the outputs in the notebook as well.

**Comment by Saptar001** [comment]
sure @geekquad

**Comment by Saptar001** [comment]
Made the asked changes @geekquad . Have a look once .

Thank You :)

**Comment by geekquad** [comment]
Hey @Saptar001, images are not loading in the notebook. 
Please have a look.

**Comment by Saptar001** [comment]
Hello @geekquad could please re-check again because the images are loading and visible pretty well, At times they are taking time to load

https://user-images.githubusercontent.com/76171314/120156329-8402b500-c20f-11eb-9295-c0e93f5d7d32.mp4

**Review by geekquad — APPROVED** [review]

**Pull request merged**
