### PR TITLE
Color Detection and Segmentation

### PR DESCRIPTION
**Pull request by Dhanush2612**
To perform invisibility cloak by implementing color detection and segmentation.
Readme file is included.

### CODE REVIEW

**Comment by geekquad** [comment]
Hey @Dhanush2612, were you assigned to this issue?
If yes then please make a reference to it. Thankyou.

**Comment by Dhanush2612** [comment]
Issue#4

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @Dhanush2612, 
please add a sample input/output in the notebook as well as README.md as well so that it will get easy for us to know the end result and will help anyone visiting for the first time.

**Comment by Dhanush2612** [comment]
@geekquad 
Will image of me holding up blanket which gets converted into cloak be enough as sample output?

**Comment by Dhanush2612** [comment]
@geekquad 
I have added sample image and video  of output.

**Comment by geekquad** [comment]
Hey @Dhanush2612, we are not accumulating projects.
Just looking for the implementation of various Image Processing techniques and not their application.
If you know some which do not already exist, please feel free to create an issue.
If I missed out on something, feel free to reopen this.

**Pull request closed without merging**
