### PR TITLE
Background subtractor

### PR DESCRIPTION
**Pull request by prithwirajmitra2001**
In response to issue #49 
Added Background Subtractor.ipynb
Gave all necessary comments and followed all the given guidelines

### CODE REVIEW

**Comment by prithwirajmitra2001** [comment]
Please add the GSSOC tag to this issue. It would help me a lot

**Comment by prithwirajmitra2001** [comment]
@geekquad 
Please check

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @prithwirajmitra2001,
Amazing work. However, in the requirements.txt file, there are a lot of unwanted packages.
Please amend that for the same.

**Comment by prithwirajmitra2001** [comment]
Okk done

**Comment by prithwirajmitra2001** [comment]
Also gssoc '21 and Level 3 tag for this PR

**Pull request merged**
