### PR TITLE
face-detection file changed

### PR DESCRIPTION
**Pull request by raj-gupta1**
face-detection file changed

### CODE REVIEW

**Comment by raj-gupta1** [comment]
Any suggestions are welcomed.

**Comment by raj-gupta1** [comment]
Added new readme file and set of instructions to be followed on face-detection

**Comment by geekquad** [comment]
Hey @raj-gupta1, were you assigned to this issue?

**Comment by raj-gupta1** [comment]
@geekquad  No, but I did it anyway which is fair. YOU get to choose which is better algo and more accurate for solving them. This is how open source works.

**Comment by geekquad** [comment]
> @geekquad No, but I did it anyway which is fair. YOU get to choose which is better algo and more accurate for solving them. This is how open source works.

Sure, will get back to you after reviewing PR from the assigned participant.

**Pull request closed without merging**
