### PR TITLE
Holistically-Nested Edge Detection

### PR DESCRIPTION
**Pull request by KKhushhalR2405**
Added code for applying HED model on an Image.

### CODE REVIEW

**Comment by KKhushhalR2405** [comment]
I have added the code for HED.  Issue Number #116

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @KKhushhalR2405, 
please read the Contributing Guidelines.
We are accepting codes only in a .ipython Notebook.
Please make the necessary changes,

**Comment by KKhushhalR2405** [comment]
I have done the requested changes. @geekquad  Kindly review the PR

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @KKhushhalR2405, 
please provide a valid description as to what the following files are doing:
- EdgeDetection/Holistically-Nested Edge Detection/deploy.prototxt
- EdgeDetection/Holistically-Nested Edge Detection/hed_pretrained_bsds.caffemodel

Also, please provide a valid description in the README.md file.
Thankyou.

**Comment by KKhushhalR2405** [comment]
I have added a description of the files and README. @geekquad Kindly review.

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @KKhushhalR2405, amazing work.
Can you please add input and output of sample images in the notebook itself?
Thankyou.

**Comment by KKhushhalR2405** [comment]
@geekquad I have made the requested changes.

**Review by geekquad — APPROVED** [review]
Hey @KKhushhalR2405, amazing work!

**Pull request merged**
