### PR TITLE
Added facial landmark detection

### LINKED ISSUE #14: Landmark Detection
Hey I would like to add facial landmark detection using Open-CV and dlib

### PR DESCRIPTION
**Pull request by akshitadixit**
This PR closes #14 

* Added facial landmark detection for static image
* Added facial landmark detection for video from camera
* Added 3 pre-trained models to detect 5, 68 and 81 points on the face respectively

### CODE REVIEW

**Comment by akshitadixit** [comment]
I'm a GSSOC participant.

**Comment by akshitadixit** [comment]
@geekquad please accept this PR so I can pull another request for issue #19

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @akshitadixit, please go through the Contributing Guidelines.
We are only accepting implementations in .ipynb form.

**Comment by akshitadixit** [comment]
@geekquad I am extremely sorry, kindly close this PR and allow me to create new ones.

**Pull request closed without merging**
