### PR TITLE
Added Prewitt Edge Detection

### LINKED ISSUE #5: Edge-Detection
I want to implement Edge Detection Algorithm. Can you please assign it to me?

### PR DESCRIPTION
**Pull request by sakshi2707**
Fixes #5 .
Please merge my PR

### CODE REVIEW

**Comment by sakshi2707** [comment]
@geekquad please merge my PR

**Comment by sakshi2707** [comment]
Thankyou @unnati914 . Can you please add gssoc and level labels in this PR?

**Comment by sakshi2707** [comment]
@unnati914 please add level 3 label in this PR as the issue has level 3 label that's why.

**Comment by raj-gupta1** [comment]
@unnati914 can you please see PR #111 which is for its next part i.e canny edge detection.

**Pull request merged**
