### PR TITLE
added the code ,image and readme file in Color Detection Folder

### PR DESCRIPTION
**Pull request by ainy-123**
kindly review my PR and merge for the issue #121 ,Color Detection using OpenCV.

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @ainy-123, please make the notebook more descriptive. 
It fails to serve the purpose. Please add proper inline comments and docstrings as required.

**Comment by ainy-123** [comment]
> Hey @ainy-123, please make the notebook more descriptive.
> It fails to serve the purpose. Please add proper inline comments and docstrings as required.

hello @geekquad I have done the changes ,you have requested for. kindly review it.

**Review by geekquad — APPROVED** [review]
Hey @ainy-123, amazing work!

**Comment by ainy-123** [comment]
> Hey @ainy-123, amazing work!

Thanks !!

**Pull request merged**
