### PR TITLE
Added Image inpainting

### PR DESCRIPTION
**Pull request by aryasoni98**
Issue #385

### CODE REVIEW

**Comment by aryasoni98** [comment]
Please review my PR @geekquad sir

**Review by geekquad — CHANGES_REQUESTED** [review]
Please add some sample Input and Output images in the notebook.

**Comment by aryasoni98** [comment]
> Please add some sample Input and Output images in the notebook.

Okay sure, I will update the notebook .

**Comment by aryasoni98** [comment]
Please review my PR

**Review by geekquad — APPROVED** [review]
Good work @aryasoni98.

**Pull request merged**
