### PR TITLE
Added face swap

### LINKED ISSUE #16: Swap faces
Would like to add face swapping feature. I am a participant of GSSOC'21

### PR DESCRIPTION
**Pull request by sudipg4112001**
### Fixed Issue
Fixes #16

### CODE REVIEW

**Comment by sudipg4112001** [comment]
Could the mentor, PA please review this PR.. For a long period of time there is no response.

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @sudipg4112001, 
please read the Contributing Guidelines. We are accepting the implementation of the techniques in .ipython notebook format. Please make the necessary changes.

**Comment by sudipg4112001** [comment]
@geekquad I have made the changes please review.

**Review by geekquad — COMMENTED** [review]
Hey @sudipg4112001, 
A few points:
1. I cannot see any implementation/ reference of the end result.
2. It is clearly mentioned that usage of only CV2 is and no external libraries/modules is allowed. 
3. No pre-trained models allowed too. 

Please see that if you can still complete the task focusing more on the implementation of the **technique** and not on its application in the face of a project/mini-project. 
Thankyou.

**Pull request closed without merging**
