### PR TITLE
added code and dependencies for CLAHE algorithm

### PR DESCRIPTION
**Pull request by ainy-123**
Fixes issue- #276

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Remove the space in the folder name.

**Comment by ainy-123** [comment]
> Remove the space in the folder name.

I have changed the folder name. Please ,have a look.

**Review by geekquad — APPROVED** [review]
Hey @ainy-123, good work.

**Comment by ainy-123** [comment]
> Hey @ainy-123, good work.

thanks.

**Pull request merged**
