### PR TITLE
Denoising algorithm

### PR DESCRIPTION
**Pull request by ShubhamGupta577**
Added code for the Denoising Algorithm.
Issue Resolved - #196
@geekquad Please review this PR.

### CODE REVIEW

**Comment by ShubhamGupta577** [comment]
@geekquad Please review this PR.

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @ShubhamGupta577, 
Please add sample input and output images in the notebook. 
Thankyou.

**Comment by ShubhamGupta577** [comment]
@geekquad, I had added the sample input/output images to the notebook as requested. Please Review the changes.

**Review by geekquad — APPROVED** [review]
Hey @ShubhamGupta577, nice work.

**Pull request merged**
