### PR TITLE
BGR2GRAY Issue#25

### PR DESCRIPTION
**Pull request by aakriti1318**
Change colour space from bgr to gray scale.

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @aakriti1318, good work.
Please go through the Contributing Guidelines. We are accepting implementations only in a .ipython notebook. Please make the necessary changes.

**Comment by aakriti1318** [comment]
> Hey @aakriti1318, good work.
> Please go through the Contributing Guidelines. We are accepting implementations only in a .ipython notebook. Please make the necessary changes.

I have changed the required changes.

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @aakriti1318, 
please remove the checkpoint file as it is not necessary. 
 I would really appreciate it if you can add sample input and output in the notebook itself. It would really help us to know the end result and will be easy to understand for anyone visiting for the first time. Thankyou.

**Review by geekquad — APPROVED** [review]
Amazing work @aakriti1318.

**Pull request merged**
